[package]
name = "save_json"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "*"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"